POST http://localhost:3000/diarioDeObra
Content-Type: application/json

{
    "idProposta": 4,
    "dataDia": "2025-10-01",
    "itensDia": "Instalação de vigas e concretagem da laje"

} 

###

GET http://localhost:3000/quantitativa/5


###
PUT http://localhost:3000/proposta/1
Content-Type: application/json

{
    "statusProposta": "REPROVADA"
}