POST http://localhost:3000/diarioDeObra
Content-Type: application/json

{
    "idProposta": 4,
    "dataDia": "2025-10-01",
    "itensDia": "Instalação de vigas e concretagem da laje"

} 

###

GET http://localhost:3000/quantitativa/5


###
PUT http://localhost:3000/proposta/1
Content-Type: application/json

{
    "statusProposta": "REPROVADA"
}

###

GET http://localhost:3000/cliente/1/propostasAprovadas

###
POST http://localhost:3000/contrato
Content-Type: application/json

{
    "idCliente": 1,
    "idProposta": 1,
    "contrato": "EduGostoso",
    "nome": "EduGostoso2.0",
    "descricao": "EduGostoso3.0",
    "local": "CasaDoKrlh"
}

###
GET http://localhost:3000/contratos

###
POST http://localhost:3000/diarioDeObra
Content-Type: application/json

{
    "idProposta": 1,
    "dataDia": "2024-10-01"
}
###

POST http://localhost:3000/diarioDeObra
Content-Type: application/json

{
    "idContrato": 1,
    "dataDia": "2024-10-01"
}



###
POST http://localhost:3000/itensDoDia
Content-Type: application/json

{
    "idDiarioDeObra": 1,
    "descricao": "teste",
    "itemQuantitativa": "teste",
    "quantidade": 2
}

###
GET http://localhost:3000/proposta/3/verAprovado

###

GET http://localhost:3000/todosOsItensDoDia

###
GET http://localhost:3000/diarioDeObraParaGraficos

###
GET http://localhost:3000/versionamentos

###
POST http://localhost:3000/criarMedicao
Content-Type: application/json

{
    "idCliente": 1,
    "obra": 1,
    "local": "Santos",
    "data": "2025-10-21",
    "periodo": "22-10 - 22-11",
    "valorTotal": 50000
}

###

GET http://localhost:3000/diarioDeObraPeriodo/2025-10-01/2025-11-15/proposta/1

###
GET http://localhost:3000/proposta/1/verAprovado

###
GET http://localhost:3000/quantitativa/1